name: cfo

channels:
  - conda-forge

dependencies:
  - python=3.7
  - jupyter=1.0.0
  - matplotlib=3.2.1
  - black
  - earthengine-api
  - flake8
  - folium
  - gdal>=3.0
  - geopandas
  - ipython
  - ipyleaflet
  - isort
  - mock
  - pandas
  - pre-commit
  - pytest
  - pytest-cov
  - rasterio
  - rtree
  - scikit-learn
  - shapely
  - pip
  - pip:
    - .
    - -r file:requirements.txt
    - pystac
